### ISSUE TITLE
webm videos ne marchent pas sur ipad

### ISSUE THREAD

**Issue by louis-ev** [sarahgarcin/dodoc-fes#21]

**Comment by louis-ev** [comment]
Il faut du mp4/h264, et des balises comme suit : 

`
<video preload="none" controls>
    <source src="http://louiseveillard.com/img/slg/au-bord.mp4" type="video/mp4">
        Dans l'amour je noierai mes pleurs
</video>
`

Idéalement, générer un thumbnail à afficher comme poster image !

**Comment by louis-ev** [comment]
même en chargeant l'url vers le mp4 dans safari ça marche pas...

**Comment by louis-ev** [comment]
![img_0695](https://cloud.githubusercontent.com/assets/1948417/8055570/c74bdf36-0ea0-11e5-82b7-caa493079c70.PNG)

**Comment by louis-ev** [comment]
Quels sont les paramètres d'encodage ? C'est du h264 ?

**Comment by louis-ev** [comment]
ça vient probablement de là...

![capture d ecran 2015-06-09 a 12 12 57](https://cloud.githubusercontent.com/assets/1948417/8055586/ebff6dca-0ea0-11e5-91c5-ef3627239ad2.png)

**Comment by louis-ev** [comment]
Tu peux changer le codec en h264 ?

**Comment by sarahgarcin** [comment]
Je vais essayer...
