### ISSUE TITLE
le bouton "go to capture" est pas du tout évident

### ISSUE THREAD

**Issue by louis-ev** [sarahgarcin/dodoc-fes#32]

**Comment by louis-ev** [comment]
Corrigé, à tester : 
![capture d ecran 2015-06-09 a 17 20 33](https://cloud.githubusercontent.com/assets/1948417/8061594/e1d2d0c8-0ecb-11e5-84e0-f86d4473944c.png)

**Comment by sarahgarcin** [comment]
C'est mieux qu'avant :)
